version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: docker build . -t jchancehud/libstorj:latest
