version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # - setup_remote_docker
      - run: |
        echo $DOCKER_USER
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - run: docker build -t jchancehud/libstorj:latest .
    - run: docker push jchancehud/libstorj:latest
