version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && docker build . -t jchancehud/libstorj:latest

workflows:
  version: 2
  deploy:
    jobs:
      - build:
        context: org-global
