version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker build . -t jchancehud/libstorj: latest
        docker push jchancehud/libstorj:latest
